version: '3.8'

services:
  bobapp-back:
    build: ./back
    container_name: bobapp-back
    ports:
      - "8080:8080"
    networks:
      - bobapp-network

  bobapp-front:
    build: ./front
    container_name: bobapp-front
    ports:
      - "4020:4020"
    depends_on:
      - bobapp-back
    networks:
      - bobapp-network

networks:
  bobapp-network:
    driver: bridge
