name: Backend tests (Tests)

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  Backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: back

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with: 
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Test with Maven
        run: mvn -B clean test

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco