name: Frontend report tests coverage

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run tests
        run: npm run test

      - name: Code coverage
        run: npm run test --code-coverage
        working-directory: front
