name: SonarCloud Frontend Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Frontend:
    name: Frontend Analysis
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: front/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests with coverage
        run: npm run test:ci
      
      - name: Debug coverage files
        run: |
          echo "=== Coverage directory content ==="
          ls -la coverage/ || echo "No coverage directory"
          echo "=== Find all lcov files ==="
          find . -name "lcov.info" -type f || echo "No lcov.info found"
          echo "=== Show coverage structure ==="
          find coverage -type f 2>/dev/null || echo "Coverage directory not found"
          echo "=== Show full tree ==="
          tree coverage/ || ls -la coverage/
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: front
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}

